sudo : required
services:
  - docker
before_install: 
  - docker build -t faysalkhan8p/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true faysalkhan8p/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstack
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-256077150132"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"